//73
// 
// This code was generated by a tool. Any changes made manually will be lost
//the next time this code is regenerated.
// 
using System.Reflection;

[assembly: AssemblyVersion("1.0.073.0806")]
[assembly: AssemblyFileVersion("1.0.073.0806")]
